name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Jekyll
        run: gem install jekyll

      - name: Build Jekyll site
        run: jekyll new ./my-site
        working-directory: ./my-site

      - name: Deploy to GitHub Pages
        run: |
          git init
          git config user.name "Eirikr-C"
          git add .
          git commit -m "Build Jekyll site"
          git branch -m main
          git remote add origin "https://github.com/Eirikr-C/Spiegel.github.io.git"
          git push -u origin main
